version: '3.6'

services:
  web:
    command: python manage.py runserver 0:8081
    environment:
      - DJANGO_ADMINS=${DJANGO_ADMINS:-[("admin", "admin@domain.invalid")]}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-*}
      - DJANGO_CSRF_COOKIE_SECURE=${DJANGO_CSRF_COOKIE_SECURE:-0}
      - DJANGO_DATABASE_SSL_REQUIRE=${DJANGO_DATABASE_SSL_REQUIRE:-0}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-1}
      - DJANGO_DEFAULT_FROM_EMAIL=${DJANGO_DEFAULT_FROM_EMAIL:-namubufferi@domain.invalid}
      - DJANGO_EMAIL_HOST=${DJANGO_EMAIL_HOST:-mail}
      - DJANGO_EMAIL_HOST_PASSWORD=${DJANGO_EMAIL_HOST_PASSWORD:-mailhog}
      - DJANGO_EMAIL_HOST_USER=${DJANGO_EMAIL_HOST_USER:-mailhog}
      - DJANGO_EMAIL_PORT=${DJANGO_EMAIL_PORT:-1025}
      - DJANGO_EMAIL_USE_SSL=${DJANGO_EMAIL_USE_SSL:-0}
      - DJANGO_EMAIL_USE_TLS=${DJANGO_EMAIL_USE_TLS:-0}
      - DJANGO_HIDDEN_ROOT=${DJANGO_HIDDEN_ROOT:-}
      - DJANGO_ONETIMEPASS_ALLOWED_DOMAINS=${DJANGO_ONETIMEPASS_ALLOWED_DOMAINS:-domain.invalid}
      - DJANGO_SECURE_HSTS_SECONDS=${DJANGO_SECURE_HSTS_SECONDS:-0}
      - DJANGO_SECURE_PROXY_SSL_HEADER=${DJANGO_SECURE_PROXY_SSL_HEADER:-0}
      - DJANGO_SECURE_SSL_REDIRECT=${DJANGO_SECURE_SSL_REDIRECT:-0}
      - DJANGO_SESSION_COOKIE_SECURE=${DJANGO_SESSION_COOKIE_SECURE:-0}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@domain.invalid}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-adminadmin}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-postgres}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
    ports:
      - '8081:8081'
    volumes:
      - virtualenvs:/usr/local/share/virtualenvs/
      - ./:/srv/namubufferi/

  mail:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

  bundler:
    image: node:16
    working_dir: /srv/namubufferi/reactapp/
    entrypoint: ./docker-entrypoint.sh
    command: yarn start
    ports:
      - '3081:3081'
    volumes:
      - reactapp_node_modules:/srv/namubufferi/reactapp/node_modules/
      - ./reactapp/:/srv/namubufferi/reactapp/

volumes:
  reactapp_node_modules:
  virtualenvs: