version: '3.9'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password

  web:
    build: .
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY_FILE=/run/secrets/django_secret_key
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - django_secret_key
      - postgres_password

secrets:
  django_secret_key:
    file: .secrets/django_secret_key.txt
  postgres_password:
    file: .secrets/postgres_password.txt

volumes:
  postgres_data:
