version: '3.6'

services:
  web:
    build: .
    environment:
      - DJANGO_SECRET_KEY_FILE=/run/secrets/django_secret_key
        #  - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - SIGNUP_SECRET=testsecret
    secrets:
      - django_secret_key
      - postgres_password
    volumes:
      - ./:/srv/namubufferi/

secrets:
  django_secret_key:
    file: .secrets/django_secret_key.txt
  postgres_password:
    file: .secrets/postgres_password.txt