# Requires Python and pip to be installed

# You must have postgresql installed.
# https://devcenter.heroku.com/articles/heroku-postgresql#local-setup
dropdb namubufferi-local-test
createdb namubufferi-local-test

# Get heroku config vars.
# https://devcenter.heroku.com/articles/heroku-local#set-up-your-local-environment-variables 
heroku config:get SENDGRID_PASSWORD -s  >> .env
heroku config:get SENDGRID_USERNAME -s  >> .env

# Create a clean venv (install virtualenv if needed)
pip install virtualenv
virtualenv venv --clear

# Install requirements in the venv
source venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt

# Apply database migrations
python manage.py migrate

# Add autogenerated data
python manage.py loadtestdata namubufferiapp.Category:5
python manage.py loadtestdata namubufferiapp.Product:30

# Create admin account
echo "___________.__        __          __                 .__     __                      .__ "
echo "\__    ___/|__| _____/  |_  _____|  | _______ _______|__|   |__| ____   ____    ____ |__|"
echo "  |    |   |  |/ __ \   __\/  ___/  |/ /\__  \\_  __ \  |   |  |/ __ \ /    \  / ___\|  |"
echo "  |    |   |  \  ___/|  |  \___ \|    <  / __ \|  | \/  |   |  \  ___/|   |  \/ /_/  >  |"
echo "  |____|   |__|\___  >__| /____  >__|_ \(____  /__|  |__/\__|  |\___  >___|  /\___  /|__|"
echo "                   \/          \/     \/     \/         \______|    \/     \//_____/     "
echo ""
echo ""
echo "Create an admin account for namupankki..."
python manage.py createsuperuser

# Good to go.
echo "You can now login to http://localhost:5000/admin with your superuser to add test stuff to namupankki."
echo "Build complete. Run server locally with 'heroku local'"

read -n1 -r -p "Press any key to start the server..."
./run.sh
