# Generated by Django 4.2.3 on 2023-08-05 16:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('name_fi', models.CharField(max_length=128, null=True, unique=True)),
                ('name_en', models.CharField(max_length=128, null=True, unique=True)),
                ('name_sv', models.CharField(max_length=128, null=True, unique=True)),
                ('name_es', models.CharField(max_length=128, null=True, unique=True)),
                ('name_ca', models.CharField(max_length=128, null=True, unique=True)),
                ('name_de', models.CharField(max_length=128, null=True, unique=True)),
                ('name_fr', models.CharField(max_length=128, null=True, unique=True)),
                ('name_it', models.CharField(max_length=128, null=True, unique=True)),
                ('name_zh_cn', models.CharField(max_length=128, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('name_fi', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('name_sv', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('name_ca', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('name_de', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('name_it', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('name_zh_cn', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='TransferSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Amount (€)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_recipient_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transfer sends',
            },
        ),
        migrations.CreateModel(
            name='TransferReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Amount (€)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_sender_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transfer receives',
            },
        ),
        migrations.CreateModel(
            name='TaggedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='ledger.product')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_translations', to='ledger.producttag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Amount (€)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_transactions', to='ledger.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='ledger.TaggedProducts', to='ledger.ProductTag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Ingress',
            fields=[
                ('concept', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Amount (€)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ingresses',
            },
        ),
    ]
