# Generated by Django 4.2.3 on 2023-07-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ingress_system',
        ),
    ]
