# Generated by Django 3.2.25 on 2025-01-27 12:41

from django.db import migrations, models


def set_committed(apps, schema_editor):
    Transaction = apps.get_model('ledger', 'Transaction')
    Transaction.objects.update(state=1)

class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'committed')], default=0),
        ),
        migrations.RunPython(set_committed),
    ]
