# Generated by Django 4.2.3 on 2023-07-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_remove_product_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_ca',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_es',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fi',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
