# Generated by Django 4.2.3 on 2023-07-30 17:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0003_product_name_ca_product_name_en_product_name_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingress',
            fields=[
                ('concept', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Amount (€)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Amount (€)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_transactions', to='ledger.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransferReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Amount (€)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_sender_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransferSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Amount (€)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_recipient_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipient_user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='MobilePayTransaction',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
