# Generated by Django 4.2.1 on 2023-05-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='price',
            new_name='amount',
        ),
    ]
