# Generated by Django 4.2.3 on 2023-07-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_ingress_purchase_transferreceive_transfersend_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingress',
            options={'verbose_name_plural': 'Ingresses'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='transferreceive',
            options={'verbose_name_plural': 'Transfer receives'},
        ),
        migrations.AlterModelOptions(
            name='transfersend',
            options={'verbose_name_plural': 'Transfer sends'},
        ),
    ]
