# Generated by Django 4.2.3 on 2023-07-30 22:20

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_product_tags_tagtranslation_customtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('name_fi', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('name_ca', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.DeleteModel(
            name='CustomTag',
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='ledger.TagTranslation', to='ledger.TranslationsTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_translations', to='ledger.translationstag'),
        ),
    ]
