# Generated by Django 4.2.3 on 2023-07-30 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_translationstag_delete_customtag_alter_product_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtranslation',
            name='content_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='ledger.product'),
        ),
    ]
