# Generated by Django 4.2.1 on 2023-06-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_alter_transaction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='concept',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
