# Generated by Django 4.2.3 on 2023-07-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_tagtranslation_content_object'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagtranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tagtranslation',
            name='language',
        ),
        migrations.RemoveField(
            model_name='tagtranslation',
            name='name',
        ),
    ]
