# Generated by Django 4.2.3 on 2023-07-30 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_alter_tagtranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TranslationsTag',
            new_name='ProductTag',
        ),
        migrations.RenameModel(
            old_name='TagTranslation',
            new_name='TaggedProducts',
        ),
    ]
