# Generated by Django 4.2.1 on 2023-06-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_transaction_recipient_user_alter_transaction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ingress_system',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
