# Generated by Django 4.2.3 on 2023-08-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_alter_ingress_user_alter_purchase_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_cn',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_de',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_it',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_sv',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producttag',
            name='name_cn',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='name_de',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='name_it',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='name_sv',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
    ]
