# Generated by Django 4.2.3 on 2023-08-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_product_name_cn_product_name_de_product_name_fr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_cn',
            new_name='name_zh',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='name_cn',
        ),
        migrations.AddField(
            model_name='producttag',
            name='name_zh',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
    ]
