# Generated by Django 4.2.3 on 2023-08-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_rename_name_cn_product_name_zh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_zh',
            new_name='name_zh_cn',
        ),
        migrations.RenameField(
            model_name='producttag',
            old_name='name_zh',
            new_name='name_zh_cn',
        ),
    ]
