# Generated by Django 3.2.11 on 2022-01-31 16:00

import uuid

from django.db import migrations, models

import onetimepass.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OneTimePass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[onetimepass.models.onetimepass_email_validator],
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("time_to_live", models.PositiveSmallIntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(default=0, editable=False),
                ),
            ],
            options={
                "verbose_name": "one-time password",
            },
        ),
    ]
