# Generated by Django 4.2.1 on 2023-06-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_terms_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_phrase', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Pass Phrase',
            },
        ),
    ]
