# Generated by Django 4.2.1 on 2023-06-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passphrase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passphrase',
            options={},
        ),
        migrations.RemoveField(
            model_name='passphrase',
            name='signup_phrase',
        ),
        migrations.AddField(
            model_name='passphrase',
            name='passphrase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
