# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namubufferiapp', '0003_auto_20160303_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=30, unique=True),
        ),
    ]
