# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 23:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('namubufferiapp', '0004_auto_20170119_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='magic_token_ttl',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 20, 23, 17, 5, 573990, tzinfo=utc)),
        ),
    ]
