# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namubufferiapp', '0006_auto_20160713_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='namubufferiapp.Transaction'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='namubufferiapp.Product'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='namubufferiapp.Transaction'),
        ),
    ]
