# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namubufferiapp', '0007_auto_20160713_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namubufferiapp.Product'),
        ),
    ]
