# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namubufferiapp', '0008_auto_20160713_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='year_in_school',
            field=models.CharField(choices=[(b'FR', b'Freshman'), (b'SO', b'Sophomore'), (b'JR', b'Junior'), (b'SR', b'Senior')], default=b'FR', max_length=2),
        ),
    ]
