# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namubufferiapp', '0009_transaction_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='namubufferiapp.Product'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[(b'P', b'Payment'), (b'D', b'Deposit'), (b'N', b'None')], default=b'N', max_length=2),
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
