# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namubufferiapp', '0012_auto_20160715_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1),
        ),
    ]
