# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namubufferiapp', '0013_auto_20160715_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=1),
        ),
    ]
