# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-12 16:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('namubufferiapp', '0013_add_tos'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
