# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-23 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namubufferiapp', '0014_auto_20160715_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
