# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-18 21:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('namubufferiapp', '0015_transaction_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='magic_link_ttl',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 18, 21, 25, 28, 69819, tzinfo=utc)),
        ),
    ]
