# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-18 22:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('namubufferiapp', '0016_userprofile_magic_link_ttl'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='magic_hash',
            field=models.CharField(default=b'CfKcJaCeg83EMCH3jtV0EEh50Zg=', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='magic_link_ttl',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 18, 22, 27, 56, 73422, tzinfo=utc)),
        ),
    ]
