# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-18 23:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('namubufferiapp', '0018_auto_20160818_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='magic_link_ttl',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 19, 0, 11, 51, 549248, tzinfo=utc)),
        ),
    ]
