# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-20 00:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('namubufferiapp', '0020_auto_20160819_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='magic_link_ttl',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 20, 1, 13, 55, 725616, tzinfo=utc)),
        ),
    ]
